steps:
  - id: build-backend
    name: 'docker'
    args:
      - build
      - --file=Dockerfile
      - '--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA'
      - '--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest'
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .
    dir: '.'

  - id: push-backend
    name: 'docker'
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    dir: '.'
    waitFor: ['build-backend']

  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'node'
    entrypoint: 'npx'
    args: ['prisma', 'migrate', 'deploy']
    secretEnv: ['DATABASE_URL']
    dir: '.'
    waitFor: ['push-backend']

timeout: 2000s
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_ACCOUNT: by-terraform

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL

# ビルド結果に生成したイメージ情報を表示する
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
