steps:
  - id: build-backend
    name: 'docker'
    args:
      - build
      - --file=Dockerfile
      - '--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA'
      - '--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest'
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .
    dir: '.'

  - id: push-backend
    name: 'docker'
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    dir: '.'
    waitFor: ['build-backend']

  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'node'
    id: 'apply-migrations'
    entrypoint: 'npx'
    args: ['prisma', 'migrate', 'deploy']
    secretEnv: ['DATABASE_URL']
    dir: '.'
    waitFor: ['push-backend']

  - id: deploy-backend
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - graphql-nestjs-backend
      - --quiet
      - --platform=managed
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --service-account=$_SERVICE_ACCOUNT
      - --revision-suffix=$SHORT_SHA
      - --tag=latest
      - --concurrency=40
      - --cpu=1
      - --memory=512Mi
      - --max-instances=3
      - --min-instances=0
      - --no-use-http2
      - --allow-unauthenticated
      - --no-cpu-throttling
      - --ingress=all
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID
      - --update-secrets=DATABASE_URL=DATABASE_URL:latest
    dir: "."
    waitFor: ["apply-migrations"]

timeout: 2000s
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_ACCOUNT: by-terraform

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL

# ビルド結果に生成したイメージ情報を表示する
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
